spring.application.name=scorebatch
server.port=8081
spring.jpa.database=mysql
spring.datasource.url=jdbc:mysql://localhost:3306/spring_batch?characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=VzbtUThUNQsW
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.generate_statistics=false
#spring.batch.jdbc.initialize-schema=always
spring.batch.job.enabled=false
#spring.batch.job.name=Second Job
